#!/bin/sh
########################################################################
# Begin bluetooth
#
# Description : BlueZ bluetoothd boot script
#
# Derived from BLFS bootscripts (BLFS 20250225) for StormFS Linux, using
# the libexec bluetoothd path and --nodetach flag from the StormFS
# bluetooth OpenRC script so both init profiles run the daemon identically.
#
########################################################################

### BEGIN INIT INFO
# Provides:            bluetooth
# Required-Start:      $local_fs dbus
# Should-Start:
# Required-Stop:       $local_fs
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts bluetooth daemons
# Description:         Starts bluetooth daemons
### END INIT INFO

. /lib/lsb/init-functions

BLUETOOTH=/usr/libexec/bluetooth/bluetoothd

case "${1}" in
   start)
      log_info_msg "Starting Bluetooth daemon bluetoothd..."
      pidlist=`pidofproc $BLUETOOTH`

      if [ "${?}" = "0" ]; then
         log_info_msg2 " Already running"
         log_success_msg2
         exit 0
      fi

      start_daemon $BLUETOOTH --nodetach
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping Bluetooth daemon bluetoothd..."
      killproc $BLUETOOTH
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc $BLUETOOTH
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0

# End bluetooth
