#!/bin/sh
########################################################################
# Begin cups
#
# Description : Start the CUPS print server
#
# Derived from BLFS bootscripts (BLFS 20250225) for StormFS Linux.
#
########################################################################

### BEGIN INIT INFO
# Provides:            cups
# Required-Start:
# Should-Start:        $syslog samba avahi
# Required-Stop:
# Should-Stop:         $syslog samba avahi
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts cups print daemon.
# Description:         Starts cups print daemon.
### END INIT INFO

. /lib/lsb/init-functions

case $1 in
   start)
      if [ ! -f /etc/cups/cupsd.conf ]; then
         log_failure_msg "/etc/cups/cupsd.conf is missing"
         exit 2
      fi
      log_info_msg "Starting CUPS Printserver..."
      start_daemon /usr/sbin/cupsd
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping CUPS Printserver..."
      killproc /usr/sbin/cupsd
      evaluate_retval
      ;;

   reload)
      log_info_msg "Reloading CUPS Printserver..."
      killproc /usr/sbin/cupsd -HUP
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc /usr/sbin/cupsd
      ;;

   *)
      echo "Usage: $0 {start|stop|reload|restart|status}"
      exit 1
      ;;
esac

exit 0

# End cups
