#!/bin/sh
########################################################################
# Begin gpm
#
# Description : Start the GPM console mouse service
#
# Derived from BLFS bootscripts (BLFS 20250225) for StormFS Linux; the
# device/protocol arguments match the StormFS GPM OpenRC script because
# the GPM port does not ship /etc/sysconfig/mouse.
#
########################################################################

### BEGIN INIT INFO
# Provides:            gpm
# Required-Start:      $local_fs udev
# Should-Start:        $syslog
# Required-Stop:       $local_fs
# Should-Stop:         $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts and stops the GPM console mouse service.
# Description:         Starts and stops the GPM console mouse service.
### END INIT INFO

. /lib/lsb/init-functions

pidfile="/run/gpm.pid"

case "${1}" in
   start)
      log_info_msg "Starting GPM console mouse service..."
      start_daemon -p "${pidfile}" /usr/sbin/gpm -m /dev/input/mice -t imps2
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping GPM console mouse service..."
      killproc /usr/sbin/gpm
      evaluate_retval
      rm -f "${pidfile}"
      ;;

   force-reload)
      # gpm does not honor SIGHUP; restart if running
      kill -0 `pidofproc -p "${pidfile}" /usr/sbin/gpm` 2>/dev/null
      if [ "${?}" = "0" ]; then
         ${0} restart
      else
         log_info_msg "Force reloading GPM console mouse service..."
         log_info_msg2 "not running"
         log_failure_msg
      fi
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc /usr/sbin/gpm
      ;;

   *)
      echo "Usage: ${0} {start|stop|force-reload|restart|status}"
      exit 1
      ;;
esac

exit 0

# End gpm
