* egui-miniquad-template
This is a template repository,
combinging the power of [[https://github.com/emilk][emilk's]] [[https://github.com/emilk/egui][egui]], [[https://github.com/not-fl3][Fedor Logachev's]] [[https://github.com/emilk/egui-miniquad][egui-miniquad]] and [[https://github.com/not-fl3/miniquad][miniquad]].

It allows you to "write once, run anywhere".

This repository is a fork of [[https://github.com/frgomes][fgromes]] [[https://github.com/frgomes/egui-miniquad-demo][egui-miniquad-demo]] but I've moved the code into the main.rs file.
And updated the whole codebase, because I upgraded the dependencies and the original code wouldn't work.
The only dependency that stayed the same is [[https://github.com/nikita-skobov][Nikita Skobov]] [[https://github.com/nikita-skobov/android-ndk-rs][ndk-glue fork]], because it was the only way I could get android building to work.

The content of the ~main.rs~ file is taken from the [[https://github.com/not-fl3/egui-miniquad/blob/master/examples/demo.rs][equi-miniquad demo example]].

** Getting started
To get started writing your own application click the ~Use template~ button to generate your own repository.
Alternatively you could also clone this repository.

Next up, you need to modify the ~Cargo.toml~ file, to contain your information.

Afterwards you can get started editing the main.rs file, or creating more files.
For some reference material,
you might want to read the [[https://docs.rs/egui-miniquad/latest/egui_miniquad/][egui-miniquad documentation]],
the [[https://docs.rs/egui/latest/egui/][egui documentation]] or
the [[https://docs.rs/miniquad/0.2.55/miniquad/][miniquad documentation]].

**NOTE: The current miniquad documentation, seems to be outdated**

** Running & Building
*** Linux
You can run this project way, you would run most of your cargo projects.
Simply run the following command to run the application.
#+BEGIN_SRC bash
cargo run
#+END_SRC

To build the software you can use the cargo build command.
#+BEGIN_SRC build
cargo build
#+END_SRC

*** Android
To be able to deploy your application to android,
you need to install [[https://github.com/dodorare/crossbow][crossbundle]].
They have their own installation instructions:
Find them [[https://github.com/dodorare/crossbow/wiki/Command-line-tool][here]].

After installing the crossbundle cli, you can use the following command to run the android app.
#+BEGIN_SRC bash
crossbundle run android --quad
#+END_SRC

To build the apk file you can use the following command.
The build artifacts can be found in `target/android/<profile/`
#+BEGIN_SRC bash
crossbundle build android --quad
#+END_SRC

** Credits
- the icons were taken from the template project generated by [[https://github.com/dodorare/crossbow][crossbundle]]
- [[https://github.com/not-fl3/miniquad][miniquad]]
- [[https://github.com/emilk/egui][egui]] immediate mode ui library
- [[https://github.com/not-fl3/egui-miniquad][egui-miniquad]] egui miniquad bindings
