modules-search: [ local ]
branding: stormfs
exec:
  - show.qml
sequence:
  - welcome
  - locale
  - keyboard
  - partition
  - mount
  - unpackfs
  - users
  - bootloader
  - initramfs
  - services-openrc
