#!/usr/bin/env python3
"""Generate non-systemd Pkgfile overlays from the upstream BFSOS ports.

The upstream recipes remain the systemd baseline. Non-systemd overlays are
applied by bootstrap.py-style copy-up before a selected base transaction.
Transformations are deliberately conservative: service units are moved to an
inactive documentation directory, while build flags and dependency metadata
are changed to avoid pulling systemd into OpenRC/SysVinit profiles.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PORTS = ROOT / "ports"
OVERLAYS = ROOT / "profiles" / "init" / "overlays"
REPORT = ROOT / "profiles" / "init" / "systemd-audit.tsv"

SYSTEMD_RE = re.compile(r"(?i)systemd|systemdsystemunitdir|libsystemd|systemctl|logind")
DEP_RE = re.compile(r"^(#\s*(?:Depends|Optional):\s*)(.*)$", re.M | re.I)


def classify(text: str) -> list[str]:
    result = []
    if re.search(r"^#\s*Depends:.*\bsystemd\b", text, re.M | re.I):
        result.append("dependency")
    if SYSTEMD_RE.search(text):
        result.append("build/runtime")
    if re.search(r"(?i)/usr/lib/systemd|systemd\.service|systemctl", text):
        result.append("service-path")
    return result


def transform(text: str, init: str) -> str:
    # Do not alter comments that describe upstream history, but remove systemd
    # from actual dependency fields so prt-get/pkgmk does not select it.
    def deps(match: re.Match[str]) -> str:
        prefix, body = match.group(1), match.group(2)
        names = body.split()
        names = [n for n in names if n.lower() != "systemd"]
        if "consolekit" not in names and ("logind" in body.lower() or "systemd" in body.lower()):
            names.append("consolekit")
        return prefix + " ".join(names)

    text = DEP_RE.sub(deps, text)

    replacements = [
        (r"-Dsystemd-user-service=enabled", "-Dsystemd-user-service=disabled"),
        (r"-Dsystemd-user-service=true", "-Dsystemd-user-service=false"),
        (r"-Dsystemd_journal=enabled", "-Dsystemd_journal=disabled"),
        (r"-Dsystemd_journal=true", "-Dsystemd_journal=false"),
        (r"-Dsystemd=enabled", "-Dsystemd=disabled"),
        (r"-Dsystemd=true", "-Dsystemd=false"),
        (r"-Dsession_tracking=systemd", "-Dsession_tracking=consolekit"),
        (r"-Dlibseat-logind=systemd", "-Dlibseat-logind=none"),
        (r"-Dsystemdsystemunitdir=[^\\\n ]+", "-Dsystemdsystemunitdir=no"),
        (r"--enable-systemd", "--disable-systemd"),
        (r"--with-systemd\b", "--without-systemd"),
        (r"--systemd-install-services", ""),
        (r"--with-systemddir=[^\\\n ]+", ""),
    ]
    for pattern, replacement in replacements:
        text = re.sub(pattern, replacement, text, flags=re.I)

    # Keep units available for inspection, but never install them into a live
    # systemd unit directory in a non-systemd build.
    text = re.sub(r"/usr/lib/systemd", "/usr/share/bfsos/systemd-units", text, flags=re.I)
    text = re.sub(r"/lib/systemd", "/usr/share/bfsos/systemd-units", text, flags=re.I)
    text = re.sub(r"\bsystemctl\b", "true # systemctl disabled for non-systemd profile", text)

    header = (
        f"# Generated by scripts/generate-init-variants.py for {init}.\n"
        "# The upstream Pkgfile remains the systemd baseline.\n"
    )
    return header + text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clean", action="store_true", help="remove generated overlays first")
    args = parser.parse_args()
    if args.clean and OVERLAYS.exists():
        for child in OVERLAYS.iterdir():
            if child.is_dir():
                import shutil
                shutil.rmtree(child)

    rows = []
    candidates = []
    for pkgfile in sorted(PORTS.rglob("Pkgfile")):
        text = pkgfile.read_text(errors="replace")
        kinds = classify(text)
        if not kinds:
            continue
        rel = pkgfile.relative_to(ROOT).as_posix()
        rows.append((rel, ",".join(kinds)))
        candidates.append((pkgfile, text))

    OVERLAYS.mkdir(parents=True, exist_ok=True)
    for init in ("openrc", "sysvinit"):
        for pkgfile, text in candidates:
            destination = OVERLAYS / init / pkgfile.relative_to(PORTS)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(transform(text, init))

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("path\tcategories\n" + "\n".join(f"{p}\t{k}" for p, k in rows) + "\n")
    print(f"audited={len(rows)} generated_per_profile={len(candidates)}")
    print(f"report={REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
